[2018-09-10 12:57:22,112 root CRITICAL] Exception:Server has wrong SHA1 thumbprint: 0e82c8dbe77b56e99a1549710bc3cf574dcdebf8 (required) != 9d13fa7aff8b7bd2aa25f2ca18701f7598adf721 (server)
[2018-09-10 12:57:22,112 root CRITICAL] Traceback (most recent call last):
   File "/build/mts/release/bora-2503622/bora/build/esxcli/release/build/Session.py", line 724, in Login
   File "/build/mts/release/bora-2503622/bora/build/esxcli/release/build/Session.py", line 853, in _GetServiceContent
   File "/build/mts/release/bora-2503622/bora/build/esxcli/release/build/pyVmomi/VmomiSupport.py", line 543, in <lambda>
   File "/build/mts/release/bora-2503622/bora/build/esxcli/release/build/pyVmomi/VmomiSupport.py", line 352, in _InvokeMethod
   File "/build/mts/release/bora-2503622/bora/build/esxcli/release/build/pyVmomi/SoapAdapter.py", line 1235, in InvokeMethod
   File "/build/mts/release/bora-2503622/bora/build/esxcli/release/build/pyVmomi/SoapAdapter.py", line 1320, in GetConnection
   File "/build/mts/release/bora-2503622/bora/build/esxcli/release/build/pyVmomi/SoapAdapter.py", line 897, in _VerifyThumbprint
 ThumbprintMismatchException: Server has wrong SHA1 thumbprint: 0e82c8dbe77b56e99a1549710bc3cf574dcdebf8 (required) != 9d13fa7aff8b7bd2aa25f2ca18701f7598adf721 (server)

[2018-09-10 13:00:14,815 root CRITICAL] Exception:
[2018-09-10 13:00:14,815 root CRITICAL] Traceback (most recent call last):
   File "/build/mts/release/bora-2503622/bora/build/esxcli/release/build/Session.py", line 758, in Login
   File "/build/mts/release/bora-2503622/bora/build/esxcli/release/build/pyVmomi/VmomiSupport.py", line 543, in <lambda>
   File "/build/mts/release/bora-2503622/bora/build/esxcli/release/build/pyVmomi/VmomiSupport.py", line 352, in _InvokeMethod
   File "/build/mts/release/bora-2503622/bora/build/esxcli/release/build/pyVmomi/SoapAdapter.py", line 1238, in InvokeMethod
   File "/build/toolchain/lin64/python-2.6.1/lib/python2.6/httplib.py", line 950, in getresponse
   File "/build/toolchain/lin64/python-2.6.1/lib/python2.6/httplib.py", line 390, in begin
   File "/build/toolchain/lin64/python-2.6.1/lib/python2.6/httplib.py", line 354, in _read_status
 BadStatusLine

